functional:
  - У пользователя должна быть возможность зарегистрироваться и авторизоваться на сайте 
  - У пользователя должна быть возможность присоединиться к играм в качестве зрителя
  - У пользователя должна быть возможность создать свою игру настроить ее по своему усмотрению
  - У пользователя должна быть возможнось вызвать на бой другого пользователя
  - У пользователя должна быть возможность принять приглашение на бой от другого пользователя
  - У пользователя должна быть возможность видеть действия противника во время игры
  - У пользователя должна быть возможность общаться через чат во время игры
  - У пользователя должна быть возможность сыграть с ботом
  - У пользователя должна быть возможность пригласить оппонента на бой по ссылке
  - У пользователя должна быть возможность настраивать свой профиль
  - У пользователя должна быть возможность участвовать в рейтинге игроков
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика 
implicit:
  - Сайт должен быть простым в использовании, с понятной навигацией
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь понятный и приятный интерфейс
